// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DbBroadcastEvent = { "eventType": "Ping", data: string, } | { "eventType": "QueryUpdated", name: string, };
