// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ordering } from "./Ordering";

export type ExecQueryRequest = { name: string, page: number | null, page_size: number | null, order_by: Array<Ordering> | null, };
