// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuerySource } from "./QuerySource";

export type Query = { name: string, source: QuerySource, };
