// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecQueryResponse } from "./ExecQueryResponse";
import type { ListQueriesResponse } from "./ListQueriesResponse";

export type RpcResponse = { "rpcType": "ListQueries" } & ListQueriesResponse | { "rpcType": "ExecQuery" } & ExecQueryResponse;
