// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecQueryRequest } from "./ExecQueryRequest";

export type RpcRequest = { "rpcType": "ListQueries" } | { "rpcType": "ExecQuery" } & ExecQueryRequest;
